apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pneumonia-api-ingress
  namespace: pneumonia
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pneumonia-api
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: pneumonia-ui
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pneumonia-ui-ingress
  namespace: pneumonia
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pneumonia-ui
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8501
